### ISSUE TITLE
Redis error

### ISSUE THREAD

**Issue by darokel** [felixclack/redis-timeline#7]
Keep running into this error whenever I try to start the server:

cannot load such file -- redis/namespace (LoadError)

Stack:

<code>
± guard  
12:49:18 - INFO - Guard uses Growl to send notifications.
12:49:18 - INFO - Guard uses TerminalTitle to send notifications.
12:49:18 - INFO - Starting Spork for RSpec, Cucumber
Using Cucumber
Using RSpec
Preloading Rails environment
/Users/david/Sites/Rails/Propertyflock/propertyflock/features/support/env.rb has not been bootstrapped.  Run spork --bootstrap to do so.
cannot load such file -- redis/namespace (LoadError)
/Users/david/.rvm/gems/ruby-1.9.3-p392@propertyflock/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `require'
/Users/david/.rvm/gems/ruby-1.9.3-p392@propertyflock/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in`block in require'
/Users/david/.rvm/gems/ruby-1.9.3-p392@propertyflock/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:236:in `load_dependency'
/Users/david/.rvm/gems/ruby-1.9.3-p392@propertyflock/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in`require'
/Users/david/.rvm/gems/ruby-1.9.3-p392@propertyflock/gems/redis-timeline-0.1.6/lib/timeline/config.rb:1:in `<top (required)>'
/Users/david/.rvm/gems/ruby-1.9.3-p392@propertyflock/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in`require'
/Users/david/.rvm/gems/ruby-1.9.3-p392@propertyflock/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `block in require'
/Users/david/.rvm/gems/ruby-1.9.3-p392@propertyflock/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:236:in`load_dependency'
/Users/david/.rvm/gems/ruby-1.9.3-p392@propertyflock/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `require'
/Users/david/.rvm/gems/ruby-1.9.3-p392@propertyflock/gems/redis-timeline-0.1.6/lib/redis-timeline.rb:4:in`<top (required)>'
/Users/david/.rvm/gems/ruby-1.9.3-p392@global/gems/bundler-1.3.3/lib/bundler/runtime.rb:72:in `require'
/Users/david/.rvm/gems/ruby-1.9.3-p392@global/gems/bundler-1.3.3/lib/bundler/runtime.rb:72:in`block (2 levels) in require'
/Users/david/.rvm/gems/ruby-1.9.3-p392@global/gems/bundler-1.3.3/lib/bundler/runtime.rb:70:in `each'
/Users/david/.rvm/gems/ruby-1.9.3-p392@global/gems/bundler-1.3.3/lib/bundler/runtime.rb:70:in`block in require'
/Users/david/.rvm/gems/ruby-1.9.3-p392@global/gems/bundler-1.3.3/lib/bundler/runtime.rb:59:in `each'
/Users/david/.rvm/gems/ruby-1.9.3-p392@global/gems/bundler-1.3.3/lib/bundler/runtime.rb:59:in`require'
/Users/david/.rvm/gems/ruby-1.9.3-p392@global/gems/bundler-1.3.3/lib/bundler.rb:132:in `require'
/Users/david/Sites/Rails/Propertyflock/propertyflock/config/application.rb:13:in`<top (required)>'
</code>

**Comment by mespina** [comment]
Add redis-namespace gem to your Gemfile

gem "redis-namespace"
