### ISSUE TITLE
Expiring tracks within timeline

### ISSUE THREAD

**Issue by petermumford** [felixclack/redis-timeline#9]
Is there a way of expiring tracks within a timeline after a certain time so the activity feed doesn't keep on growing? I can't see why you would want to keep tracks which are months old.

**Comment by felixclack** [comment]
There isn't a way to do this at the moment, but if you have any ideas how you'd like to implement it, I'd be happy to consider a PR.

**Comment by petermumford** [comment]
Ok. I'll have a look and do some thinking.

Meanwhile, do you know how I could create a track on the fly so its not created on a callback? So something like `track_now :new_like ..., ...`
